/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import DAO.DichVuDao;
import Utils.msg;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.Dichvu;

/**
 *
 * @author Vie
 */
public class DichVu extends javax.swing.JDialog {

    /**
     * Creates new form DichVuj
     */
    DichVuDao dvd = new DichVuDao();
    int index = -1;

    public DichVu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loatable();
        setLocationRelativeTo(parent);
    }

    void loatable() {
        DefaultTableModel model = (DefaultTableModel) tbldv.getModel();
        model.setRowCount(0);
        try {
            List<Dichvu> list = dvd.selectAll();
            for (Dichvu item : list) {
                Object[] row = {
                    item.getTen(), item.getGia(), item.getMoTa()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    public void edit() {
        String ma = (String) tbldv.getValueAt(index, 0);
        Dichvu nv = dvd.selectById(ma);
        setform(nv);
    }

    public void setform(Dichvu dv) {
        txtten.setText(dv.getTen());
        txtgia.setText(dv.getGia() + "");
        txtmt.setText(dv.getMoTa());
    }

    public void home() {
        index = 0;
        edit();
    }

    public void end() {
        index = tbldv.getRowCount() - 1;
        edit();
    }

    public void next() {
        if (index > 0) {
            index = index - 1;
            edit();
        } else {
            index = tbldv.getRowCount() - 1;
            edit();
        }
    }

    public void back() {
        if (index < tbldv.getRowCount() - 1) {
            index = index + 1;
            edit();
        } else {
            index = 0;
            edit();
        }
    }

    public Dichvu getformm() {
        Dichvu dv = new Dichvu();
        dv.setTen(txtten.getText());
        dv.setGia(Double.valueOf(txtgia.getText()));
        dv.setMoTa(txtmt.getText());
        return dv;
    }

    public void clear() {
        Dichvu dv = new Dichvu();
        setform(dv);
        index = -1;
    }

    public void them() {
        Dichvu dv = getformm();
        try {
            dvd.insert(dv);
            loatable();
            clear();
            msg.alert(this, "Thêm Thành Công");
        } catch (Exception e) {
            msg.alert(this, "Thêm Thất bại");
        }
    }

    public void xoa() {
        String id = txtten.getText();
        if (msg.confirm(this, "Bạn Có Muốn Xoá Không")) {
            try {
                dvd.delete(id);
                loatable();
                msg.alert(this, "xoá Thành Công");
            } catch (Exception e) {
                msg.alert(this, "xoá Thất bại");
                e.printStackTrace();
            }
        }

    }

    public void sua() {
        try {
            Dichvu nh = getformm();
            dvd.update(nh);
            loatable();
            msg.alert(this, "cập nhật  Thành Công");
        } catch (Exception e) {
            msg.alert(this, "cập nhật Thất bại");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel1 = new design.MyPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldv = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmt = new javax.swing.JTextArea();
        txtten = new design.MyTextField3();
        txtgia = new design.MyTextField3();
        myButton5 = new design.MyButton();
        myButton9 = new design.MyButton();
        myButton10 = new design.MyButton();
        myButton11 = new design.MyButton();
        myButton12 = new design.MyButton();
        myButton13 = new design.MyButton();
        myButton14 = new design.MyButton();
        myButton15 = new design.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        myPanel1.setTenAnh("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dịch Vụ");

        tbldv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Dịch Vụ", "Giá", "Mô Tả"
            }
        ));
        tbldv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbldvMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbldv);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mô Tả :");

        txtmt.setColumns(20);
        txtmt.setRows(5);
        jScrollPane2.setViewportView(txtmt);

        txtten.setLabelText("Tên Dịch Vụ");
        txtten.setSelectedTextColor(new java.awt.Color(51, 51, 255));

        txtgia.setLabelText("Giá");

        myButton5.setText("Sửa");
        myButton5.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton5.setColor(new java.awt.Color(244, 212, 253));
        myButton5.setColorClick(new java.awt.Color(154, 240, 255));
        myButton5.setColorOver(new java.awt.Color(154, 240, 255));
        myButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton5.setRadius(30);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });

        myButton9.setText("Mới");
        myButton9.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton9.setColor(new java.awt.Color(244, 212, 253));
        myButton9.setColorClick(new java.awt.Color(154, 240, 255));
        myButton9.setColorOver(new java.awt.Color(154, 240, 255));
        myButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton9.setRadius(30);
        myButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton9ActionPerformed(evt);
            }
        });

        myButton10.setText("Thêm");
        myButton10.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton10.setColor(new java.awt.Color(244, 212, 253));
        myButton10.setColorClick(new java.awt.Color(154, 240, 255));
        myButton10.setColorOver(new java.awt.Color(154, 240, 255));
        myButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton10.setRadius(30);
        myButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton10ActionPerformed(evt);
            }
        });

        myButton11.setText("Xoá");
        myButton11.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton11.setColor(new java.awt.Color(244, 212, 253));
        myButton11.setColorClick(new java.awt.Color(154, 240, 255));
        myButton11.setColorOver(new java.awt.Color(154, 240, 255));
        myButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton11.setRadius(30);
        myButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton11ActionPerformed(evt);
            }
        });

        myButton12.setText("|<");
        myButton12.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton12.setColor(new java.awt.Color(244, 212, 253));
        myButton12.setColorClick(new java.awt.Color(154, 240, 255));
        myButton12.setColorOver(new java.awt.Color(154, 240, 255));
        myButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton12.setRadius(30);
        myButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton12ActionPerformed(evt);
            }
        });

        myButton13.setText("<<");
        myButton13.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton13.setColor(new java.awt.Color(244, 212, 253));
        myButton13.setColorClick(new java.awt.Color(154, 240, 255));
        myButton13.setColorOver(new java.awt.Color(154, 240, 255));
        myButton13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton13.setRadius(30);
        myButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton13ActionPerformed(evt);
            }
        });

        myButton14.setText(">>");
        myButton14.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton14.setColor(new java.awt.Color(244, 212, 253));
        myButton14.setColorClick(new java.awt.Color(154, 240, 255));
        myButton14.setColorOver(new java.awt.Color(154, 240, 255));
        myButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton14.setRadius(30);
        myButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton14ActionPerformed(evt);
            }
        });

        myButton15.setText(">|");
        myButton15.setBorderColor(new java.awt.Color(166, 219, 253));
        myButton15.setColor(new java.awt.Color(244, 212, 253));
        myButton15.setColorClick(new java.awt.Color(154, 240, 255));
        myButton15.setColorOver(new java.awt.Color(154, 240, 255));
        myButton15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton15.setRadius(30);
        myButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(myButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1))
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbldvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldvMousePressed
        index = tbldv.getSelectedRow();
        edit();
    }//GEN-LAST:event_tbldvMousePressed

    private void myButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton12ActionPerformed
        home();
    }//GEN-LAST:event_myButton12ActionPerformed

    private void myButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton13ActionPerformed
        next();
    }//GEN-LAST:event_myButton13ActionPerformed

    private void myButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton14ActionPerformed
        back();
    }//GEN-LAST:event_myButton14ActionPerformed

    private void myButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton15ActionPerformed
        end();
    }//GEN-LAST:event_myButton15ActionPerformed

    private void myButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton9ActionPerformed
        clear();
    }//GEN-LAST:event_myButton9ActionPerformed

    private void myButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton10ActionPerformed
        them();
    }//GEN-LAST:event_myButton10ActionPerformed

    private void myButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton11ActionPerformed
        xoa();
    }//GEN-LAST:event_myButton11ActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        sua();
    }//GEN-LAST:event_myButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DichVu dialog = new DichVu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private design.MyButton myButton10;
    private design.MyButton myButton11;
    private design.MyButton myButton12;
    private design.MyButton myButton13;
    private design.MyButton myButton14;
    private design.MyButton myButton15;
    private design.MyButton myButton5;
    private design.MyButton myButton9;
    private design.MyPanel myPanel1;
    private javax.swing.JTable tbldv;
    private design.MyTextField3 txtgia;
    private javax.swing.JTextArea txtmt;
    private design.MyTextField3 txtten;
    // End of variables declaration//GEN-END:variables
}
