/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import DAO.LoaiPhongDAO;
import Utils.msg;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.LoaiPhong;

/**
 *
 * @author anhta
 */
public class QuanLyLoaiPhong extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyLoaiPhong
     *
     * @param parent
     * @param modal
     */
    public QuanLyLoaiPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();

    }
    LoaiPhongDAO loaiPhongDAO = new LoaiPhongDAO();
    int selectedRowCount = 0;

    public void init() {
        fillComboboxSoNguoi();
        fillTable();
    }

    public void fillTable() {
        List<LoaiPhong> list = loaiPhongDAO.selectAll();
        fillTable0(list);
    }

    public void fillTable0(List<LoaiPhong> list) {
        DefaultTableModel model = (DefaultTableModel) tblLoaiPhong.getModel();
        model.setRowCount(0);
        try {
            for (LoaiPhong lp : list) {
                Object[] row = {
                    lp.getIdLP(),
                    String.valueOf(lp.getGia()),
                    String.valueOf(lp.getSoNguoi())
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            msg.alert(this, "Lỗi truy vấn dữ liệu!");
        }

    }

    public void fillComboboxSoNguoi() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSoNguoi.getModel();
        for (int i = 0; i < 20; i++) {
            model.addElement(i + 1);
        }

    }

    private void search() {
        String searchInput = txtSearch.getText();
        try {
            List<LoaiPhong> list = loaiPhongDAO.selectByID(searchInput);
            fillTable0(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel1 = new design.MyPanel();
        jLabel1 = new javax.swing.JLabel();
        panelOpacity1 = new design.PanelOpacity();
        panelOpacity2 = new design.PanelOpacity();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiPhong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new design.MyTextField();
        panelOpacity3 = new design.PanelOpacity();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenLP = new design.MyTextField();
        txtDonGia = new design.MyTextField();
        cboSoNguoi = new javax.swing.JComboBox<>();
        btnAdd = new design.MyButton();
        btnDelete = new design.MyButton();
        btnUpdate = new design.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        myPanel1.setTenAnh("1c2e14cb40299d77c4386.jpg");
        myPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOẠI PHÒNG");
        jLabel1.setPreferredSize(new java.awt.Dimension(37, 30));
        myPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        panelOpacity1.setLayout(new java.awt.GridLayout(1, 2));

        tblLoaiPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên loại phòng", "Đơn giá", "Số người"
            }
        ));
        tblLoaiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLoaiPhongMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiPhong);

        jLabel2.setText("Tìm kiếm:");

        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelOpacity2Layout = new javax.swing.GroupLayout(panelOpacity2);
        panelOpacity2.setLayout(panelOpacity2Layout);
        panelOpacity2Layout.setHorizontalGroup(
            panelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacity2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addGroup(panelOpacity2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOpacity2Layout.setVerticalGroup(
            panelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacity2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpacity2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOpacity1.add(panelOpacity2);

        jLabel3.setText("Tên loại phòng:");

        jLabel4.setText("Đơn giá:");

        jLabel5.setText("Số người:");

        txtTenLP.setForeground(new java.awt.Color(0, 0, 0));

        txtDonGia.setForeground(new java.awt.Color(0, 0, 0));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpacity3Layout = new javax.swing.GroupLayout(panelOpacity3);
        panelOpacity3.setLayout(panelOpacity3Layout);
        panelOpacity3Layout.setHorizontalGroup(
            panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacity3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpacity3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOpacity3Layout.createSequentialGroup()
                                .addComponent(cboSoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 203, Short.MAX_VALUE))
                            .addComponent(txtTenLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelOpacity3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelOpacity3Layout.setVerticalGroup(
            panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpacity3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenLP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboSoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        panelOpacity1.add(panelOpacity3);

        myPanel1.add(panelOpacity1, java.awt.BorderLayout.CENTER);

        getContentPane().add(myPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoaiPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiPhongMousePressed
        selectedRowCount = tblLoaiPhong.getSelectedRow();
        displaySelectedRow();
    }//GEN-LAST:event_tblLoaiPhongMousePressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        insert();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        search();
    }//GEN-LAST:event_txtSearchKeyReleased

    public LoaiPhong getLoaiPhong() {
        LoaiPhong loaiPhong = new LoaiPhong();
        loaiPhong.setIdLP(txtTenLP.getText());
        loaiPhong.setGia(Float.parseFloat(txtDonGia.getText()));
        loaiPhong.setSoNguoi((int) cboSoNguoi.getSelectedItem());
        return loaiPhong;
    }

    public void insert() {
        try {
            loaiPhongDAO.insert(getLoaiPhong());
            msg.alert(this, "Added!");
            fillTable();
        } catch (Exception e) {
            msg.alert(this, "Fail Added!");
            e.printStackTrace();
        }
    }

    public void delete() {
        try {
            loaiPhongDAO.delete(txtTenLP.getText());
            msg.alert(this, "Deleted!");
            fillTable();
        } catch (Exception e) {
            msg.alert(this, "Fail Delete!");
            e.printStackTrace();
        }
    }

    public void update() {
        try {
            loaiPhongDAO.update(getLoaiPhong());
            msg.alert(this, "Updated!");
            fillTable();
        } catch (Exception e) {
            msg.alert(this, "Fail Update!");
            e.printStackTrace();
        }
    }

    public void displaySelectedRow() {
        System.out.println("Selected Row: " + selectedRowCount);
        tblLoaiPhong.setRowSelectionInterval(selectedRowCount, selectedRowCount);
        txtTenLP.setText(tblLoaiPhong.getValueAt(selectedRowCount, 0).toString());
        txtDonGia.setText(tblLoaiPhong.getValueAt(selectedRowCount, 1).toString());
        cboSoNguoi.setSelectedItem(Integer.valueOf(tblLoaiPhong.getValueAt(selectedRowCount, 2).toString()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyLoaiPhong dialog = new QuanLyLoaiPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private design.MyButton btnAdd;
    private design.MyButton btnDelete;
    private design.MyButton btnUpdate;
    private javax.swing.JComboBox<String> cboSoNguoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private design.MyPanel myPanel1;
    private design.PanelOpacity panelOpacity1;
    private design.PanelOpacity panelOpacity2;
    private design.PanelOpacity panelOpacity3;
    private javax.swing.JTable tblLoaiPhong;
    private design.MyTextField txtDonGia;
    private design.MyTextField txtSearch;
    private design.MyTextField txtTenLP;
    // End of variables declaration//GEN-END:variables
}
